### ISSUE TITLE
Logo lokaal te overrulen?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#10]
Het te gebruiken logo wordt nu in de organization configuration gedefinieerd m.b.v. de 'logos' property (zie ook [issue 9](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/issues/9)). Het is echter mogelijk om dit lokaal te overrulen.

Ik heb daarover de volgende vragen:
* willen we het lokaal overrulen van deze property toestaan?<br/>Kunnen we ons situaties indenken dat dit gewenst is? 
* zo ja, kunnen we dan beschrijven wanneer het is toegestaan?

Indien we er samen voor kiezen dat deze property niet lokaal overruled mag worden dan betreft dat een werkafspraak. Dit kan dan helaas niet afgedwongen worden.

**Comment by hdksi** [comment]
Een afwijkend logo mag, maar het ligt voor de hand hiervoor alleen te kiezen bij een afwijkende `nl_organisationName`.

**Comment by melsk-r** [comment]
Je opmerking is in de documentatie opgenomen.
