### ISSUE TITLE
Mogelijkheid om TOC niveaus lokaal te definiëren?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#11]
Default worden alle Table of Content niveau's opgenomen maar dit kun je inperken met de configuration property 'maxTocLevel'. Met de configuration property 'noTOC' en de waarde 'true' kun je het genereren van een Table of Content overigens blokkeren.

Ik heb daarover de volgende vragen:
* vinden we het toegestaan het genereren van de Table of Content lokaal te blokkeren?
* willen we het aantal niveau's al globaal inperken?<br/>Zo ja, op hoeveel niveau’s willen we dit dan instellen? 
* staan we het toe dat dit lokaal gewijzigd moet kunnen worden?

Indien we er samen voor kiezen dat de 'noTOC' en/of de 'maxTocLevel' property niet lokaal gebruikt mag worden dan betreft dat een werkafspraak. Dit kan dan helaas niet afgedwongen worden.

**Comment by hdksi** [comment]
Wat een handige table of content is, is naar mijn verwachting erg afhankelijk van het soort artefact dat de Respec beschrijft. Ik zou vrij aanpassen van beide property's daarom toestaan.

**Comment by melsk-r** [comment]
@hdksi Ben je niet van mening dat er wel altijd een TOC moet worden gegenereerd?

**Comment by melsk-r** [comment]
In documentatie opgenomen dat beide properties lokaal overruled kunnen worden.
