### ISSUE TITLE
Vaste organisatienaam of willen we dit kunnen wijzigen

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#12]
Op dit moment is de organisatienaam m.b.v. de configuratie property 'nl_organisationName' in de organization configuration gedefinieerd. Dit heeft nu de waarde 'VNG Realisatie'. 

Ik heb daarover de volgende vragen:
* is dit inderdaad de gewenste globale waarde?<br/>**Let op!** als we een ander logo dan het VNG Realisatie logo willen (zie [issue 9](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/issues/9)) dan willen we hier wellicht ook een andere naam. 
* vinden we dat de organisatienaam lokaal aangepast moet kunnen worden?

Indien we er samen voor kiezen dat deze property niet lokaal aangepast mag worden dan betreft dat een werkafspraak. Dit kan dan helaas niet afgedwongen worden.

**Comment by adgerrits** [comment]
'Lokaal tenzij' lijkt me (ook) hier wenselijker dan 'Globaal tenzij' omdat er in de praktijk allerlei redenen kunnen zijn waarom een globale setting niet klopt. Eerder bijv. door VNGR een project Notificatieservices gedaan waarbij BZK eigenaar was en waar ook [een specificatie via ReSpec](https://vng-realisatie.github.io/NL-GOV-profile-for-CloudEvents/) werd gepubliceerd.
In lijn met 'lokaal tenzij' moet er dus een hele goede reden zijn om een globale setting niet lokaal te kunnen wijzigen. Wat nu globaal geldig lijkt te zijn kan heel snel niet meer geldig zijn.

**Comment by hdksi** [comment]
Eens met Ad. Een defaultoptie is nuttig, maar die moet wel overschreven kunnen worden.

**Comment by melsk-r** [comment]
In de documentatie is nu aangegeven dat deze property lokaal overruled kan worden. Bij communicatie staat de vraag uit of de default waarde 'VNG Realisatie' of 'VNG' moet zijn. Gerelateerd met issue #9.

**Comment by melsk-r** [comment]
Communicatie geeft het advies om 'VNG Realisatie' aan te houden. Met name omdat de doelgroep van onze Respec documentatie over het algemeen specifiek VNG Realisatie op de radar heeft.
