### ISSUE TITLE
Altijd een pdf genereren of die keuze over laten aan document eigenaar?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#13]
Het genereren van een pdf bestand wordt geconfigureerd met de configuration property 'alternateFormats' in de document configuration. Het is helaas niet mogelijk dit als een globale property te definiëren. 

Ik heb hierover de volgende vragen:
* vinden we dat een document eigenaar deze configuration property mag verwijderen uit zijn lokale configuratie zodat er geen pdf wordt gegenereerd?
* willen we deze configuratie property globaal kunnen definiëren?

Indien we er samen voor kiezen dat deze property niet lokaal verwijderd mag worden dan betreft dat een werkafspraak. Dit kan dan helaas niet afgedwongen worden.

Persoonlijk zie ik zo geen redenen waarom er geen pdf gegenereerd zou moeten worden dus ik adviseer niet toe te staan om deze property te verwijderen. Ik stel dan ook voor een issue in te dienen om het mogelijk te maken deze property ook in de globale configuratie te definiëren.

**Let op!** Deze property zorgt niet alleen voor het genereren van een pdf maar ook voor het plaatsen van een link naar deze pdf in het document (zie hieronder).

![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/3e8c04d6-fa23-47e0-b97a-a5882851a87d)

**Comment by hdksi** [comment]
Het aanbieden van een PDF-versie lijkt me een mooie service. Maar ik kan me voorstellen dat je voor vroege werkversies juist níet wil dat varianten in een duurzaam formaat gaan circuleren. Verplichten zou ik het genereren van een PDF daarom niet.

**Comment by melsk-r** [comment]
Goed punt, daar had ik nog niet aan gedacht. Ik ben het eens met je. Ik wijzig daarom mijn voorstel en stel voor dat documenteigenaren de property 'alternateFormats' mag uitbecommentariëren of verwijderen.

**Comment by melsk-r** [comment]
Documentatie is zo aangepast dat property uit becommentarieerd mag worden.
