### ISSUE TITLE
Is het gebruik van de ‘github’ property optioneel?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#14]
De 'github' configuration property wordt lokaal in de document configuration gedefinieerd en wordt gebruikt voor het genereren van de links in de 'Doe mee' alinea bovenin de Respec documentatie (zie hieronder).

![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/85f93cd9-66d2-40ff-b651-4ffbbf8ce8c2)

Het bevat een link naar de GitHub repository waarin het Informatiemodel wordt beheerd. Indien het niet wordt gedefinieerd dan wordt de 'Doe mee' alinea niet gegenereerd.

Ik heb daarover de volgende vraag:
* vinden we het acceptabel de ‘github’ property niet te definiëren?

Indien we er samen voor kiezen dat deze property altijd aanwezig moet zijn dan betreft dat een werkafspraak. Dit kan dan helaas niet afgedwongen worden.

Ik zie geen redenen om de 'Doe mee' alinea niet te genereren dus ik stel voor niet toe te staan deze property te verwijderen.

**Comment by hdksi** [comment]
Ja, het niet vullen van deze proprerty vind ik acceptabel. Bijvoorbeeld voor artefacten die formeel(!) niet meer worden beheerd of voor artefacten waarvan de 'bron' repo buiten Github leeft.

**Comment by melsk-r** [comment]
Dan blijft de documentatie ongewijzigd.
