### ISSUE TITLE
Respec documentatie met of zonder links (§)?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#2]
M.b.v. de configuratie property 'addSectionLinks' kunnen paragraaftekens (§) voor de secties gegenereerd worden zoals in onderstaande voorbeeld is gedaan.:

![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/74a14b16-6a63-4f41-bd61-d1ca8699735c)

Indien we hiervoor kiezen kunnen de lezers van het Respec document, door met je rechtermuistoets te klikken op het paragraaf teken , de url naar die sectie kopiëren waarna ze deze in een ander document kunnen plakken. Zo creëer je dus een directe link naar de betreffende sectie. Op dit moment is dit een globale property met de waarde 'false' waardoor ze niet gegenereerd worden. Deze property kan echter lokaal overruled worden.

Willen we inderdaad dat deze globaal de waarde 'false' heeft?
Vinden we het toegestaan dat deze lokaal overruled kan worden?

Logius lijkt de gewoonte te hebben het paragraaf teken mee te genereren (zie [deze voorbeelden](https://logius-standaarden.github.io/publicatie/)). Bij Geonovum en Kadaster wijken de diverse Respec documenten van elkaar af op dit punt.  Voor W3C documenten worden de paragraaftekens standaard wel mee gegenereerd.

Ik heb niet echt een sterke mening over het wel of niet tonen van het paragraaf teken. Ik vind wel dat we alle Respec documenten binnen VNG-R op dit punt op dezelfde wijze moeten genereren. Eenheid uitstralen vind ik van belang. Ik zou er dan ook voor kiezen het niet toe te staan deze property lokaal te overrulen. 

**LET OP!**: Dat laatste is een afspraak die we samen maken, dit kan (nog) niet afgedwongen worden.

**Comment by hdksi** [comment]
Meeste stemmen van toepassende partijen gelden; met paragraafteken dus wat mij betreft ;)

**Comment by melsk-r** [comment]
Is als zodanig gedocumenteerd. Lokaal overrulen is toegestaan.
