### ISSUE TITLE
Vanaf welke versie publiceren we Respec documentatie?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#20]
Vanaf welke versie vinden we dat Respec documentatie gepubliceerd moet worden via de publicatie repository?
Moet dat al met de eerste beta versies gebeuren of pas vanaf de eerste major release?
Of kunnen we een aantal criteria benoemen op basis waarvan we dit kunnen bepalen?

**Comment by hdksi** [comment]
Ik weet niet of dit makkelijk te formaliseren is. In hele vroege iteraties of voor het informeren van specifieke doelgroepen kan ik me voorstellen dat publicatie van een eenvoudige afbeelding van een model volstaat en/of dat juist een minder formele presentatiewijze gewenst is. Verplichting tot publicatie via Respec kan immers onterecht de indruk wekken dat sprake is van enige volwassenheid.

In de praktijk ontwikkelen we maar beperkt nieuwe informatiemodellen. Wellicht dit voorlopig van geval tot geval bekijken?

**Comment by melsk-r** [comment]
Ok, ik sluit dit issue.
