### ISSUE TITLE
Welke kleuren voor de verschillende specStatus waardes in het label linksboven

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#4]
Op basis van de 'specStatus' property wordt de kleur van het label linksboven 

![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/2ea17ef7-1096-414e-98d0-ec2dcaf32804)

bepaald. Deze wordt geconfigureerd in de property 'labelColor' welke op dit moment de volgende waardes heeft:

def: "#154273",  ![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/4e9c7e34-3e63-4373-a59b-fe00cd18c6d4)
wv: "#39870c",   ![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/d3dd499d-1a9c-434a-9c71-c3be70826ba4)
ig: "#A569BD",   ![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/b58f1250-885d-4d91-9167-95a22d4fe5c8)
io: "#DC7633"    ![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/18a781cf-6bb8-481b-a5a5-c6afe1186fb8)

Indien wij dezelfde statussen hanteren als andere organisaties is het denk ik goed dezelfde kleuren te hanteren. Voor nieuwe statussen ('ig' en 'io') zullen we echter zelf kleuren moeten kiezen. Tenzij we besluiten om de codes 'def' en 'wv' te vervangen door 'ig' en 'io' (zie [issue 3](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/issues/3)). In dat geval adviseer ik om ook de daarbij horende kleuren over te nemen zodat we in pas blijven lopen met bijv. Geonovum.

Indien we nog andere codes dan hierboven gaan hanteren dan stel ik voor daar ook kleurcodes voor te kiezen.

**Comment by hdksi** [comment]
Ik zou niet aan bestaande conventies gaan tornen en dus nieuwe kleuren introduceren. Rood en geel zijn zo te zien nog vrij ;)

**Comment by melsk-r** [comment]
@hdksi De kleuren bij 'io' en 'ig' zijn door mij geïntroduceerd. Een evt. nieuwe status zou idd de kleur rood kunnen krijgen. Geel is prima als de achtergrond zwart is maar dat is niet het geval.

**Comment by melsk-r** [comment]
In de property 'labelColor' zijn de kleuren voor de statussen 'def' en 'wv' verwijderd omdat deze statussen ook verwijderd zijn.
