### ISSUE TITLE
Over welke specType waardes willen wij in Respec documenten kunnen beschikken?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#5]
In het organisatie configuratie bestand worden in de property 'localizationStrings' de volgende specificatietypes gedefinieerd:
```
basis: "Document",
no: "Norm",
st: "Standaard",
im: "Informatiemodel",
pr: "Praktijkrichtlijn",
hr: "Handreiking",
wa: "Werkafspraak",
al: "Algemeen",
bd: "Beheerdocumentatie",
bp: "Best practice",
```
De teksten achter de codes worden in onze Respec documentatie opgenomen in de subtitel of in het label linksboven (zie hieronder).

![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/db02ed9b-a958-472e-a9d2-a1b319e63e39)

Ik heb hierover de volgende vragen:

* Welke van deze types kunnen verwijderd worden?
De code 'im' moet sowieso blijven bestaan, daar is het bij het onderzoek naar Respec immers om te doen geweest.
De code 'hr' gebruik ik nu voor de documentatie over Respec al is dat meer een 'Handleiding' dan een 'Handreiking'.
* Moeten er nog types aan toegevoegd worden?

Het is dus eigenlijk de vraag voor welk type documentatie we Respec willen gebruiken. Overigens kunnen we deze lijst altijd uitbreiden. Lijkt me echter goed om deze lijst nu op te schonen zodat we een goed gebruik afdwingen.

**Comment by hdksi** [comment]
> Lijkt me echter goed om deze lijst nu op te schonen zodat we een goed gebruik afdwingen.

Ik zou inderdaad beginnen met alleen de types/codes die gebruikt worden. En aanvullen wanneer dat opportuun is.

**Comment by melsk-r** [comment]
Alle types zijn uit becommentarieerd behalve 'im' en 'hr'. De laatste is hernoemd naar 'hl' (Handleiding).
