### ISSUE TITLE
Willen we dat het licentie type lokaal overruled kan worden?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#6]
M.b.v. de configuration property 'license' kan het van toepassing zijnde licentietype gedefinieerd worden. Deze configuratie property is nu opgenomen in de organization configuration met de waarde 'EUPL'.

De vraag is of we daarvan af willen kunnen wijken en bijv. willen kunnen kiezen voor 
* Creative Commons 0 Public Domain Dedication;
* Creative Commons Attribution 4.0 International Public License.

of nog een geheel andere licentietype? Indien we er samen voor kiezen dat deze property niet lokaal overruled mag worden dan betreft dat een werkafspraak. Dit kan dan helaas niet afgedwongen worden.

**Comment by adgerrits** [comment]
Net als bij alle andere vragen over 'wel/niet lokaal te overrulen' zou ik in zijn algemeenheid kiezen voor 'lokaal te overrulen'. De wereld verandert vaak sneller dan je denkt.

**Comment by hdksi** [comment]
Eens met Ad.

**Comment by melsk-r** [comment]
Is als zodanig gedocumenteerd.
