### ISSUE TITLE
Welke te gebruiken referenties moeten er globaal gedefinieerd worden?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#7]
Het is mogelijk om referenties te configureren en daar dan in de documentatie naar te verwijzen m.b.v. de configuratie property 'localBiblio' (zie betreffende configuratie property in de [paragraaf over configuratie properties](https://vng-realisatie.github.io/publicatie/cim/respec-template/#functie-respec-configuratie-properties)). Dit kan zowel globaal, voor referenties die in meerdere documenten opgenomen moeten kunnen worden, als lokaal, voor referenties die slechts voor een of enkele documenten beschikbaar moeten zijn.

Deze referenties worden dan opgenomen in de bijlage 'Referenties' (zie hieronder):

![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/7c8faaf9-040c-4476-8a64-e24854d2b614)

De paragraaf 'Normatieve referenties' bevat dan de in de normatieve hoofdstukken opgenomen referenties en de paragraaf 'Informatieve referenties' de in de informatieve hoofdstukken opgenomen referenties. 

Ik heb hierover de volgende vragen:
* Welke referenties onderkennen wij waarvan wij vinden dat ze in meerdere documenten opgenomen moeten kunnen worden?
* Het wordt aangemoedigd om referenties aan te melden bij [de SpecRef database](https://www.specref.org/). Welke referenties die daar niet al in voorkomen willen we daar opgenomen hebben?

**Comment by hdksi** [comment]
Ik kan deze vraag niet goed beantwoorden. Lijkt me iets om naar aanleiding van publicatie van concrete modellen te bepalen.

**Comment by melsk-r** [comment]
> Ik kan deze vraag niet goed beantwoorden. Lijkt me iets om naar aanleiding van publicatie van concrete modellen te bepalen.

Deze lijst zal zich inderdaad langzamerhand uitbreiden. 

> Als handreiking voor normatieve referenties zouden we nog kunnen opnemen dat in ieder geval verwijzingen naar wetgeving en standaarden op de ['Pas toe leg uit'-lijst](https://www.forumstandaardisatie.nl/open-standaarden/verplicht) van het Forum Standaardisatie of de [Gemeentelijke standaardenlijst](https://vng.nl/artikelen/overzicht-gemeentelijke-standaarden) met verbindendheid 'pas-toe-of-leg-uit' en 'verplicht' als zodanig moeten worden beschouwd.

Dit is opgenomen in de documentatie.
