### ISSUE TITLE
VNG Realisatie logo, ander logo of geen logo?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/VNG-R-Respec-Organization-configurations#9]
Op dit moment is in de organization configuration m.b.v. de 'logos' property gedefinieerd dat rechtsboven in een Respec document van VNG-R het VNG Realisatie logo wordt geplaatst (zie hieronder):

![image](https://github.com/VNG-Realisatie/VNG-R-Respec-Organization-configurations/assets/20185784/569f016d-87e8-45bd-9a51-8a95a00ce8aa)

Ik heb daarover de volgende vragen:
* kiezen we inderdaad voor het VNG Realisatie logo?
* willen we daar een ander logo (bijv. het VNG logo)?
* of willen we helemaal geen logo?

De laatste optie is n.m.m. helemaal geen optie.

**Comment by hdksi** [comment]
Ik heb geen voorkeur, maar dit lijkt me een vraag voor de afdeling communicatie.

**Comment by melsk-r** [comment]
In de documentatie is nu aangegeven dat deze property lokaal overruled kan worden. Bij communicatie staat de vraag uit of het default logo dat van VNG Realisatie of dat van VNG moet zijn. Gerelateerd meet issue #12.

**Comment by melsk-r** [comment]
Communicatie geeft het advies om het VNG Realisatie logo aan te houden. Met name omdat de doelgroep van onze Respec documentatie over het algemeen specifiek VNG Realisatie op de radar heeft.
